# @package _global_

defaults:
  - default_1k_4dim       # This loads everytjing fron config/default.yaml
  - _self_


# Overrides
run_name: "biggermodel_10k_2dim_${now:%m%d_%H%M}"
batch_size: 4     # Smaller to accomodate for larger batch size
model:
  trm_model:
    L_layers: 4
    hidden_size: 512
    num_heads: 8

# Data Config
data:
  train_problems_dir: 'data/regression_2dim/train/10000/problems'
  train_solutions_dir: 'data/regression_2dim/train/10000/solutions'