# @package _global_

defaults:
  - default_1k_4dim       # This loads everytjing fron config/default.yaml
  - _self_

# Overrides
run_name: "default_1k_4dim_${now:%m%d_%H%M}"

# Data Config
data:
  train_problems_dir: 'data/regression_2dim/train/10000/problems'
  train_solutions_dir: 'data/regression_2dim/train/10000/solutions'