# @package _global_

defaults:
  - default_1k_2dim       # This loads everytjing fron config/default.yaml
  - _self_

# Project & Run Config
project_name: "trm-dev"
run_name: "default_1k_4dim_${now:%m%d_%H%M}"
checkpoint_dir: 'checkpoints/'
resume_from: null

# Core Hyperparameters
batch_size: 24
lr: 1e-4
num_epochs: 1000

# Experiment-specific
act_loss_weight: 0.01
epsilon: 0.5

# Data Config
data:
  train_problems_dir: 'data/regression_4dim/train/1000/problems'
  train_solutions_dir: 'data/regression_4dim/train/1000/solutions'
  val_problems_dir: 'data/regression_4dim/val/300/problems'
  val_solutions_dir: 'data/regression_4dim/val/300/solutions'
  num_workers: 4
