# @package _global_

defaults:
  - default       # This loads everytjing fron config/default.yaml
  - _self_


# Overrides
run_name: "bigger_model_v1_${now:%m%d_%H%M}"
batch_size: 4     # Smaller to accomodate for larger batch size
model:
  trm_model:
    L_layers: 4
    hidden_size: 512
    num_heads: 8