# @package _global_

defaults:
  - default       # This loads everytjing fron config/default.yaml
  - _self_


# Overrides
run_name: "default_v1_10k_${now:%m%d_%H%M}"

# Data Config
data:
  train_problems_dir: 'data/v1/train/10000/problems'
  train_solutions_dir: 'data/v1/train/10000/solutions'